name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: M1_projectGoal_AppUtill/.github/workflows/c-cpp.yml
    - name: Install Dependencies
      run: npn install
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
